import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "1rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        sans: ['"Readex Pro"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'micro': ['11px', { lineHeight: '14px' }],
        'caption': ['12px', { lineHeight: '16px' }],
        'label': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body': ['14px', { lineHeight: '20px' }],
        'body-lg': ['15px', { lineHeight: '22px' }],
        'h3': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'h2': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'h1': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'display': ['28px', { lineHeight: '34px', fontWeight: '700' }],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          light: "hsl(var(--primary-light))",
          dark: "hsl(var(--primary-dark))",
          bg: "hsl(var(--primary-bg))",
          disabled: "hsl(var(--primary-disabled))",
        },
        p2: "hsl(var(--p2))",
        s1: { DEFAULT: "hsl(var(--s1))", dark: "hsl(var(--s1-dark))" },
        s2: "hsl(var(--s2))",
        ksa: {
          yellow: "hsl(var(--ksa-yellow))",
          "yellow-dark": "hsl(var(--ksa-yellow-dark))",
          green: "hsl(var(--ksa-green))",
          red: "hsl(var(--ksa-red))",
        },
        tabby: { DEFAULT: "hsl(var(--tabby-mint))", text: "hsl(var(--tabby-mint-text))" },
        tamara: { DEFAULT: "hsl(var(--tamara-purple))", text: "hsl(var(--tamara-purple-text))" },
        success: { DEFAULT: "hsl(var(--success))", bg: "hsl(var(--success-bg))", text: "hsl(var(--success-text))" },
        warning: { DEFAULT: "hsl(var(--warning))", bg: "hsl(var(--warning-bg))", text: "hsl(var(--warning-text))" },
        info: { DEFAULT: "hsl(var(--info))", bg: "hsl(var(--info-bg))", text: "hsl(var(--info-text))" },
        n1: "hsl(var(--n1))",
        n2: "hsl(var(--n2))",
        n3: "hsl(var(--n3))",
        n4: "hsl(var(--n4))",
        n6: "hsl(var(--n6))",
        n7: "hsl(var(--n7))",
        n8: "hsl(var(--n8))",
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        'card': '16px',
        'input': '12px',
      },
      backgroundImage: {
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-ramadan': 'var(--gradient-ramadan)',
        'gradient-eid': 'var(--gradient-eid)',
        'gradient-success': 'var(--gradient-success)',
        'gradient-onboarding': 'var(--gradient-onboarding)',
      },
      boxShadow: {
        'elev1': 'var(--shadow-elev1)',
        'elev2': 'var(--shadow-elev2)',
        'cta': 'var(--shadow-cta)',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'smooth': 'cubic-bezier(0.22, 1, 0.36, 1)',
        'snappy': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      keyframes: {
        "accordion-down": { from: { height: "0", opacity: "0" }, to: { height: "var(--radix-accordion-content-height)", opacity: "1" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)", opacity: "1" }, to: { height: "0", opacity: "0" } },
        "fade-in":        { "0%": { opacity: "0", transform: "translateY(8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "fade-out":       { "0%": { opacity: "1", transform: "translateY(0)" },  "100%": { opacity: "0", transform: "translateY(8px)" } },
        "scale-in":       { "0%": { opacity: "0", transform: "scale(0.96)" },    "100%": { opacity: "1", transform: "scale(1)" } },
        "scale-out":      { "0%": { opacity: "1", transform: "scale(1)" },       "100%": { opacity: "0", transform: "scale(0.96)" } },
        "slide-in-right": { "0%": { transform: "translateX(16px)", opacity: "0" }, "100%": { transform: "translateX(0)", opacity: "1" } },
        "slide-in-left":  { "0%": { transform: "translateX(-16px)", opacity: "0" }, "100%": { transform: "translateX(0)", opacity: "1" } },
        "slide-up":       { "0%": { opacity: "0", transform: "translateY(16px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "slide-down":     { "0%": { opacity: "0", transform: "translateY(-12px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "shimmer":        { "0%": { backgroundPosition: "200% 0" }, "100%": { backgroundPosition: "-200% 0" } },
        "pulse-ring":     { "0%": { boxShadow: "0 0 0 0 hsl(var(--primary) / 0.45)" }, "100%": { boxShadow: "0 0 0 14px hsl(var(--primary) / 0)" } },
        "float":          { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-4px)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.24s cubic-bezier(0.22,1,0.36,1)",
        "accordion-up":   "accordion-up 0.2s cubic-bezier(0.22,1,0.36,1)",
        "fade-in":        "fade-in 0.35s cubic-bezier(0.22,1,0.36,1) both",
        "fade-out":       "fade-out 0.25s cubic-bezier(0.22,1,0.36,1) both",
        "scale-in":       "scale-in 0.28s cubic-bezier(0.34,1.56,0.64,1) both",
        "scale-out":      "scale-out 0.2s ease-in both",
        "slide-in-right": "slide-in-right 0.32s cubic-bezier(0.22,1,0.36,1) both",
        "slide-in-left":  "slide-in-left 0.32s cubic-bezier(0.22,1,0.36,1) both",
        "slide-up":       "slide-up 0.4s cubic-bezier(0.22,1,0.36,1) both",
        "slide-down":     "slide-down 0.3s cubic-bezier(0.22,1,0.36,1) both",
        "enter":          "fade-in 0.35s cubic-bezier(0.22,1,0.36,1) both, scale-in 0.28s cubic-bezier(0.34,1.56,0.64,1) both",
        "pulse-ring":     "pulse-ring 1.4s cubic-bezier(0.22,1,0.36,1) infinite",
        "float":          "float 3s ease-in-out infinite",
        "shimmer":        "shimmer 1.4s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
