import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "1rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        sans: ['"Readex Pro"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'micro': ['11px', { lineHeight: '14px' }],
        'caption': ['12px', { lineHeight: '16px' }],
        'label': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body': ['14px', { lineHeight: '20px' }],
        'body-lg': ['15px', { lineHeight: '22px' }],
        'h3': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'h2': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'h1': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'display': ['28px', { lineHeight: '34px', fontWeight: '700' }],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          light: "hsl(var(--primary-light))",
          dark: "hsl(var(--primary-dark))",
          bg: "hsl(var(--primary-bg))",
          disabled: "hsl(var(--primary-disabled))",
        },
        p2: "hsl(var(--p2))",
        s1: { DEFAULT: "hsl(var(--s1))", dark: "hsl(var(--s1-dark))" },
        s2: "hsl(var(--s2))",
        success: { DEFAULT: "hsl(var(--success))", bg: "hsl(var(--success-bg))", text: "hsl(var(--success-text))" },
        warning: { DEFAULT: "hsl(var(--warning))", bg: "hsl(var(--warning-bg))", text: "hsl(var(--warning-text))" },
        info: { DEFAULT: "hsl(var(--info))", text: "hsl(var(--info-text))" },
        n1: "hsl(var(--n1))",
        n2: "hsl(var(--n2))",
        n3: "hsl(var(--n3))",
        n4: "hsl(var(--n4))",
        n6: "hsl(var(--n6))",
        n7: "hsl(var(--n7))",
        n8: "hsl(var(--n8))",
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        'card': '16px',
        'input': '12px',
      },
      backgroundImage: {
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-ramadan': 'var(--gradient-ramadan)',
        'gradient-eid': 'var(--gradient-eid)',
        'gradient-success': 'var(--gradient-success)',
        'gradient-onboarding': 'var(--gradient-onboarding)',
      },
      boxShadow: {
        'elev1': 'var(--shadow-elev1)',
        'elev2': 'var(--shadow-elev2)',
        'cta': 'var(--shadow-cta)',
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
